image:
  name: docker/compose:latest

services:
  - docker:dind

before_script:
  - docker version
  - docker-compose version

# build:
#   stage: build
#   script:
#     - docker-compose down
#     - docker-compose build

# test-api:
#   stage: test
#   script:
#     - docker-compose build api
#     - docker-compose run api rake db:create
#     - docker-compose run api rake db:migrate
#     - docker-compose run api bundle exec rails test

test-web:
  stage: build
  variables:
    NODE_ENV: test
  script: 
    - echo $env:NODE_ENV
    - docker-compose run web yarn run test:unit

# code_quality: