image:
  name: docker/compose:latest

services:
  - docker:dind

stages:
  - build
  - test
  - quality

before_script:
  - docker version
  - docker-compose version

build:
  stage: build
  script:
    - docker-compose down
    - docker-compose build

test_api:
  stage: test
  script:
    - docker-compose build api
    - docker-compose run api rake db:create
    - docker-compose run api rake db:migrate
    - docker-compose run api bundle exec rails test

test_web:
  stage: test
  script: 
    - docker-compose build web
    - docker-compose run web yarn install
    - docker-compose run web yarn run test:unit

code_quality:
  stage: quality
  image : docker:stable
  services:
    - docker:dind
  allow_failure: true
  script:
    - mkdir public
    - docker pull codeclimate/codeclimate:latest
    - docker run --name hatoum --env CODECLIMATE_DEBUG=1 --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate:0.85.4 analyze -f html > codeclimate.html
    - mv codeclimate.html public
  artifacts:
    paths: 
      - public/
  tags :
    - ci_test
  only:
    refs:
        - feature/with-docker-compose
    variables:
        - $PIPELINE_MODE == "medium"
        - $PIPELINE_MODE == "advanced"