image:
  name: docker/compose:1.26.0

services:
  - docker:dind

before_script:
  - docker version
  - docker-compose version

build:
  stage: build
  script:
    - docker-compose down
    - docker-compose build -t trab-image .

test-api:
  stage: test
  script: docker-compose run api bundle exec rails test

test-web:
  stage: test
  script: docker-compose run web yarn run test:unit

# code_quality: