version: "3.8"
services:
  db:
    image: postgres
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    # TODO: create a file.sh to run commands
    command: bash -c "rm -f tmp/pids/server.pid && rake db:create && rake db:migrate && exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/api
    ports:
      - "3000:3000"
    depends_on:
      - db
  web:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    # TODO: create a file.sh to run commands
    command: bash -c "yarn install && yarn dev"
    volumes:
      - ./client:/client
      - ./client/yarn_cache:/client/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - api